- name: config profile
  copy: src=files/profile dest=/etc/profile

- name: config bashrc
  copy: src=files/bash.bashrc dest=/etc/bash.bashrc

#- name: make-linux-fast-again
#  lineinfile: dest=/etc/default/grub regexp=^GRUB_CMDLINE_LINUX_DEFAULT line='GRUB_CMDLINE_LINUX_DEFAULT="quiet splash noibrs noibpb nopti nospectre_v2 nospectre_v1 l1tf=off nospec_store_bypass_disable no_stf_barrier mds=off tsx=on tsx_async_abort=off mitigations=off"'
