---
- name: Create ANTs directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/opt/quarantine/software/ANTs/{{ ants_version }}/install"

- name: Install ANTs install dependencies
  ansible.builtin.apt:
    update_cache: true
    state: present
    autoclean: true
    autoremove: true
    pkg:
      - unzip

- name: Install ANTs
  unarchive:
    src: "https://github.com/ANTsX/ANTs/releases/download/v{{ ants_version }}/ants-{{ ants_version }}-ubuntu-{{ ansible_distribution_version }}-X64-gcc.zip"
    dest: "/opt/quarantine/software/ANTs/{{ ants_version }}/install"
    creates: "/opt/quarantine/software/ANTs/{{ ants_version }}/install/bin/antsRegistration"
    remote_src: yes

- name: Move ANTs install files
  shell: "mv /opt/quarantine/software/ANTs/{{ ants_version }}/install/ants-{{ ants_version }}/* /opt/quarantine/software/ANTs/{{ ants_version }}/install"
  args:
    creates: "/opt/quarantine/software/ANTs/{{ ants_version }}/install/bin/antsRegistration"

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: "/opt/quarantine/software/ANTs/{{ ants_version }}/module"
  notify: link modules
