---
- name: Create ANTs directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/quarantine/software/ANTs/2.5.3/install

- name: Install ANTs install dependencies
  ansible.builtin.apt:
    update_cache: true
    state: present
    autoclean: true
    autoremove: true
    pkg:
      - unzip

- name: Install ANTs
  unarchive:
    src: https://github.com/ANTsX/ANTs/releases/download/v2.5.3/ants-2.5.3-ubuntu-24.04-X64-gcc.zip
    dest: /opt/quarantine/software/ANTs/2.5.3/install
    creates: /opt/quarantine/software/ANTs/2.5.3/install/bin/antsRegistration
    remote_src: yes

- name: Move ANTs install files
  shell: mv /opt/quarantine/software/ANTs/2.5.3/install/ants-2.5.3/* /opt/quarantine/software/ANTs/2.5.3/install
  args:
    creates: /opt/quarantine/software/ANTs/2.5.3/install/bin/antsRegistration

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/ANTs/2.5.3/module
  notify: link modules
