---

- name: add apptainer ppa
  command: apt-add-repository -y -n {{ item }}
  with_items:
    - ppa:apptainer/ppa

- name: Install apptainer dependencies
  ansible.builtin.apt:
    update_cache: true
    state: present
    autoclean: true
    autoremove: true
    pkg:
      - apptainer

# Apptainer has messed up their ubuntu ppa, need to manually install the new version for now
- name: install apptainer release deb
  apt: deb=https://github.com/apptainer/apptainer/releases/download/v1.3.6/apptainer_1.3.6_amd64.deb
  ignore_errors: yes
