---

- name: add apptainer ppa
  command: apt-add-repository -y -n {{ item }}
  with_items:
    - ppa:apptainer/ppa

- name: Install apptainer dependencies
  ansible.builtin.apt:
    update_cache: true
    state: present
    autoclean: true
    autoremove: true
    pkg:
      - apptainer
