---
- name: Create fmriprep directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/quarantine/software/fmriprep/24.1.1/install
    - /opt/quarantine/software/fmriprep/20.2.8/install


- name: Build fmriprep singularity container
  command: apptainer build /opt/quarantine/software/fmriprep/24.1.1/install/fmriprep docker://nipreps/fmriprep:24.1.1
  args:
    creates: /opt/quarantine/software/fmriprep/24.1.1/install/fmriprep

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/fmriprep/24.1.1/module
  notify: link modules

#######LTS Version

- name: Build fmriprep singularity container
  command: apptainer build /opt/quarantine/software/fmriprep/20.2.8/install/fmriprep docker://nipreps/fmriprep:20.2.8
  args:
    creates: /opt/quarantine/software/fmriprep/20.2.8/install/fmriprep

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/fmriprep/20.2.8/module
  notify: link modules