---
- name: Create MATLAB Module directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/quarantine/software/PLS/6.15/install
    - /opt/quarantine/software/SPM12/r7771/install
    - /opt/quarantine/software/CAT12/12.8.2/install
    - /opt/quarantine/software/BrainNetViewer/1.7/install

- name: Download MATLAB PLS
  unarchive:
    src: https://github.com/McIntosh-Lab/PLS/archive/refs/tags/6.15.tar.gz
    dest: /opt/quarantine/software/PLS/6.15/install
    creates: /opt/quarantine/software/PLS/6.15/install/plsgui
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/PLS/6.15/module
  vars:
    prereqs:
      - matlab
    extra_opts:
      - prepend_path( "MATLABPATH", pathJoin(basepath,"plscmd"))
      - prepend_path( "MATLABPATH", pathJoin(basepath,"plsgui"))
  notify: link modules

- name: Download SPM
  unarchive:
    src: https://www.fil.ion.ucl.ac.uk/spm/download/restricted/eldorado/spm12.zip
    dest: /opt/quarantine/software/SPM12/r7771/install
    creates: /opt/quarantine/software/SPM12/r7771/install/spm12
    remote_src: yes

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/SPM12/r7771/module
  vars:
    prereqs:
      - matlab
    extra_opts:
      - prepend_path( "MATLABPATH", pathJoin(basepath,"spm12"))
  notify: link modules

- name: Download SPM
  unarchive:
    src: https://github.com/ChristianGaser/cat12/releases/download/12.8.2/cat12.8.2.zip
    dest: /opt/quarantine/software/CAT12/12.8.2/install
    creates: /opt/quarantine/software/CAT12/12.8.2/install/cat12
    remote_src: yes

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/CAT12/12.8.2/module
  vars:
    prereqs:
      - matlab
      - SPM12
    extra_opts:
      - prepend_path( "MATLABPATH", pathJoin(basepath,"cat12"))
      - prepend_path( "MATLABPATH", pathJoin(basepath))
  notify: link modules

- name: Create SPM defaults file for CAT12 loading
  copy:
    content: |
              global defaults
              defaults.tbx.dir{end+1} = fullfile(fileparts(mfilename('fullpath')),"CAT12") ;
    dest: /opt/quarantine/software/CAT12/12.8.2/install/spm_my_defaults.m

- name: Download BrainNetViewer
  unarchive:
    src: https://www.nitrc.org/frs/download.php/11580/BrainNetViewer_20191031.zip
    dest: /opt/quarantine/software/BrainNetViewer/1.7/install
    creates: /opt/quarantine/software/BrainNetViewer/1.7/install/BrainNet.m
    remote_src: yes

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/BrainNetViewer/1.7/module
  vars:
    prereqs:
      - matlab
    extra_opts:
      - prepend_path( "MATLABPATH", pathJoin(basepath))
  notify: link modules