---
- name: install mrtrix3
  shell: micromamba create --quiet --yes -c mrtrix3 -p /opt/quarantine/software/mrtrix3/3.0.4/mrtrix3 mrtrix3=3.0.4
  args:
    creates: /opt/quarantine/software/mrtrix3/3.0.4/mrtrix3/bin/mrcalc

- name: Install module
  template:
    src: templates/conda_module.j2
    dest: /opt/quarantine/software/mrtrix3/3.0.4/module
  vars:
    modulename: mrtrix3
  notify: link modules