---
- name: Create nvidia module directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/quarantine/software/nvhpc/24.3/src

- name: Install nvidia development dependencies
  ansible.builtin.apt:
    update_cache: yes
    state: present
    autoclean: yes
    autoremove: yes
    pkg:
      - g++
      - freeglut3-dev
      - build-essential
      - libx11-dev
      - libxmu-dev
      - libxi-dev
      - libglu1-mesa-dev
      - libfreeimage-dev
      - libglfw3-dev

- name: Download nvhpc
  unarchive:
    src: https://developer.download.nvidia.com/hpc-sdk/24.3/nvhpc_2024_243_Linux_x86_64_cuda_multi.tar.gz
    dest: /opt/quarantine/software/nvhpc/24.3/src
    creates: /opt/quarantine/software/nvhpc/24.3/install/modulefiles # We rely on a file created by the installation so this isn't re-downloaded
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Run nvhpc Installer
  ansible.builtin.shell: NVHPC_SILENT=true NVHPC_INSTALL_DIR=/opt/quarantine/software/nvhpc/24.3/install NVHPC_INSTALL_TYPE=auto /opt/quarantine/software/nvhpc/24.3/src/install
  args:
    creates: /opt/quarantine/software/nvhpc/24.3/install/modulefiles

- name: Cleanup downloaded nvhpc source
  ansible.builtin.file:
    path: /opt/quarantine/software/nvhpc/24.3/src
    state: absent

- name: copy nvidia module activate
  copy: src=files/zznvidia_modules.sh dest=/etc/profile.d
