---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/quarantine/software/R/4.3
    - /opt/quarantine/software/rstudio/2024.04.1-74/install

- name: copy R environment file
  copy: src=files/neuroimaging_R.yml dest=/opt/quarantine/software/R/4.3/

- name: create R environment
  shell: micromamba create --quiet --yes -p /opt/quarantine/software/R/4.3/r-base -f /opt/quarantine/software/R/4.3/neuroimaging_R.yml
  args:
    creates: /opt/quarantine/software/R/4.3/r-base/bin/R

- name: Install module
  template:
    src: templates/conda_module.j2
    dest: /opt/quarantine/software/R/4.3/module
  vars:
    modulename: r-base
  notify: link modules

# - name: Install RMINC (R)
#   shell: . /opt/minc/1.9.18/minc-toolkit-config.sh && Rscript --vanilla -e 'remotes::install_github("Mouse-Imaging-Centre/RMINC@*release", upgrade=FALSE)'
#   args:
#     creates: /usr/local/lib/R/site-library/RMINC
#   when:
#     - '"R" in ansible_run_tags or "all" in ansible_run_tags'

# - name: Install MRIcrotome (R)
#   shell: Rscript --vanilla -e 'remotes::install_github("Mouse-Imaging-Centre/MRIcrotome", upgrade=FALSE)'
#   args:
#     creates: /usr/local/lib/R/site-library/MRIcrotome
#   when:
#     - '"R" in ansible_run_tags or "all" in ansible_run_tags'

- name: Install mni_cortical_statistics (R)
  shell: micromamba run -r /opt/quarantine/software/R/4.3/r-base Rscript --vanilla -e 'pak::pkg_install("BIC-MNI/mni.cortical.statistics")'
  args:
    creates: /opt/quarantine/software/R/4.3/r-base/lib/R/library/mni.cortical.statistics

- name: Install rstudio
  unarchive:
    src: https://download1.rstudio.org/electron/jammy/amd64/rstudio-2024.04.1-748-amd64-debian.tar.gz
    dest: /opt/quarantine/software/rstudio/2024.04.1-74/install
    creates:  /opt/quarantine/software/rstudio/2024.04.1-74/install/b
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/rstudio/2024.04.1-74/module
  vars:
    prereqs:
      - R
  notify: link modules
