---

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/quarantine/software/R/4.3
    - /opt/quarantine/software/rstudio/2024.09.0-368/install
    - /opt/quarantine/software/RMINC/1.5.3.1/install
    - /opt/quarantine/software/MRIcrotome/2aed2ff/install
    - /opt/quarantine/software/mni.cortical.statistics/4bc1388/install

- name: copy R environment file
  copy: src=files/neuroimaging_R.yml dest=/opt/quarantine/software/R/4.3/

- name: create R environment
  shell: micromamba create --quiet --yes -p /opt/quarantine/software/R/4.3/r-base -f /opt/quarantine/software/R/4.3/neuroimaging_R.yml
  args:
    creates: /opt/quarantine/software/R/4.3/r-base/bin/R

# Needed so that adding additional packages work
- name: copy condarc file
  copy: src=files/condarc dest=/opt/quarantine/software/R/4.3/r-base

- name: Install module
  template:
    src: templates/conda_module.j2
    dest: /opt/quarantine/software/R/4.3/module
  vars:
    modulename: r-base
  notify: link modules

- name: Install RMINC (R)
  shell: >
        LD_LIBRARY_PATH=/opt/quarantine/software/minc-toolkit-v2/1.9.18/install/lib
        PATH=/opt/quarantine/software/minc-toolkit-v2/1.9.18/install/bin:${PATH}
        MINC_PATH=/opt/quarantine/software/minc-toolkit-v2/1.9.18/install
        micromamba run -r /opt/quarantine/software/R/4.3/r-base Rscript --vanilla --verbose
        -e ' withr::with_libpaths(new = "/opt/quarantine/software/RMINC/1.5.3.1/install", action="prefix", remotes::install_github("Mouse-Imaging-Centre/RMINC@develop", upgrade=FALSE))'
  args:
    creates: /opt/quarantine/software/RMINC/1.5.3.1/install/RMINC
  when:
    - '"minc" in ansible_run_tags or "all" in ansible_run_tags'

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/RMINC/1.5.3.1/module
  vars:
    prereqs:
      - R
    extra_opts:
      - prepend_path( "R_LIBS", basepath)
  notify: link modules

- name: Install MRIcrotome (R)
  shell: >
        R_LIBS=/opt/quarantine/software/RMINC/1.5.3.1/install
        micromamba run -r /opt/quarantine/software/R/4.3/r-base
        Rscript --vanilla --verbose -e 'withr::with_libpaths(new = "/opt/quarantine/software/MRIcrotome/2aed2ff/install", action="prefix", remotes::install_github("Mouse-Imaging-Centre/MRIcrotome@2aed2ff", upgrade=FALSE))'
  args:
    creates: /opt/quarantine/software/MRIcrotome/2aed2ff/install/MRIcrotome
  when:
    - '"minc" in ansible_run_tags or "all" in ansible_run_tags'

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/MRIcrotome/2aed2ff/module
  vars:
    prereqs:
      - R
    extra_opts:
      - prepend_path( "R_LIBS", basepath)
  notify: link modules

- name: Install mni_cortical_statistics (R)
  shell: >
        micromamba run -r /opt/quarantine/software/R/4.3/r-base
        Rscript --vanilla --verbose -e 'withr::with_libpaths(new = "/opt/quarantine/software/mni.cortical.statistics/4bc1388/install", action="prefix", remotes::install_github("BIC-MNI/mni.cortical.statistics@4bc1388", upgrade=FALSE))'
  args:
    creates: /opt/quarantine/software/mni.cortical.statistics/4bc1388/install/mni.cortical.statistics

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/mni.cortical.statistics/4bc1388/module
  vars:
    prereqs:
      - R
    extra_opts:
      - prepend_path( "R_LIBS", basepath)
  notify: link modules


- name: Install rstudio
  unarchive:
    src: "https://s3.amazonaws.com/rstudio-ide-build/electron/jammy/amd64/rstudio-2024.09.0-368-amd64-debian.tar.gz"
    dest: /opt/quarantine/software/rstudio/2024.09.0-368/install
    creates:  /opt/quarantine/software/rstudio/2024.09.0-368/install/rstudio
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Install module
  template:
    src: templates/basemodule.j2
    dest: /opt/quarantine/software/rstudio/2024.09.0-368/module
  vars:
    prereqs:
      - R
  notify: link modules
