---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/quarantine/software/R/4.1.3
    - /etc/conda

# Ensure conda config is correct
- name: copy condarc
  copy: src=files/condarc dest=/etc/conda/condarc

# Install pipx
- name: Install pipx
  ansible.builtin.apt:
    update_cache: yes
    state: present
    autoclean: yes
    autoremove: yes
    pkg: pipx

# pipx directory
- name: ensure /opt/pipx
  ansible.builtin.file:
    path: /opt/pipx
    state: directory
    mode: 0755

- name: install radian
  community.general.pipx:
    name: "{{ item }}"
    state: present
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin
  with_items:
    - radian

- name: copy R environment file
  copy: src=files/neuroimaging_R.yml dest=/opt/quarantine/software/R/4.1.3/

- name: create R environment
  shell: micromamba create --quiet --yes -p /opt/quarantine/software/R/4.1.3/r-base -f /opt/quarantine/software/R/4.1.3/neuroimaging_R.yml
  args:
    creates: /opt/quarantine/software/R/4.1.3/r-base/bin/R

- name: Install module
  template:
    src: templates/conda_module.j2
    dest: /opt/quarantine/software/R/4.1.3/module
  vars:
    modulename: r-base
  notify: link modules

# - name: Install RMINC (R)
#   shell: . /opt/minc/1.9.18/minc-toolkit-config.sh && Rscript --vanilla -e 'remotes::install_github("Mouse-Imaging-Centre/RMINC@*release", upgrade=FALSE)'
#   args:
#     creates: /usr/local/lib/R/site-library/RMINC
#   when:
#     - '"R" in ansible_run_tags or "all" in ansible_run_tags'

# - name: Install MRIcrotome (R)
#   shell: Rscript --vanilla -e 'remotes::install_github("Mouse-Imaging-Centre/MRIcrotome", upgrade=FALSE)'
#   args:
#     creates: /usr/local/lib/R/site-library/MRIcrotome
#   when:
#     - '"R" in ansible_run_tags or "all" in ansible_run_tags'

- name: Install mni_cortical_statistics (R)
  shell: micromamba run -r /opt/quarantine/software/R/4.1.3/r-base Rscript --vanilla -e 'pak::pkg_install("BIC-MNI/mni.cortical.statistics")'
  args:
    creates: /opt/quarantine/software/R/4.1.3/r-base/lib/R/library/mni.cortical.statistics
