---
- name: create directory for atlas files for {{ (item | basename | splitext)[0] }}
  file:
    path: /opt/quarantine/resources/{{ (item | basename | splitext)[0] }}
    state: directory

- name: Download atlas files for {{ (item | basename | splitext)[0] }}
  unarchive:
    src: "{{ item }}"
    dest: /opt/quarantine/resources/{{ (item | basename | splitext)[0] }}
    creates: /opt/quarantine/resources/{{ (item | basename | splitext)[0] }}/COPYING
    remote_src: yes
